image: gitpod/workspace-java-17

tasks:
  - init: ./gradlew publishToMavenLocal

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven

